name: Deploy Next.js to Azure Web App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: "vm1d5d" # Replace with your Azure Web App name
  NODE_VERSION: "22.x"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js application
        run: npm run build
        env:
          NODE_ENV: production

      - name: Run linting
        run: npm run lint

      - name: Create deployment package
        run: |
          # Create a clean directory for deployment
          mkdir deployment-package

          # Copy necessary files
          cp -r .next deployment-package/
          cp -r public deployment-package/
          cp package.json deployment-package/
          cp package-lock.json deployment-package/
          cp server.js deployment-package/
          cp web.config deployment-package/
          cp startup.txt deployment-package/

          # Copy other config files if they exist
          [ -f next.config.js ] && cp next.config.js deployment-package/
          [ -f tailwind.config.js ] && cp tailwind.config.js deployment-package/
          [ -f postcss.config.js ] && cp postcss.config.js deployment-package/
          [ -f tsconfig.json ] && cp tsconfig.json deployment-package/

          # Copy app and components directories
          cp -r app deployment-package/
          cp -r components deployment-package/

      - name: "Deploy to Azure Web App"
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: "./deployment-package"

      - name: "Post-deployment verification"
        run: |
          echo "Deployment completed successfully!"
          echo "App should be available at: https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net"

