# Optimized GitHub Actions workflow for Next.js deployment to Azure Web App
name: Build and deploy Next.js app to Azure Web App - nkhcfg

on:
  push:
    branches:
      - master # Change to 'master' if that's your default branch
  workflow_dispatch:

env:
  NODE_VERSION: "22.x"
  AZURE_WEBAPP_NAME: "nkhcfg"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4 # Updated to v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci # Faster than npm install

      - name: Run linting
        run: npm run lint

      - name: Build Next.js application
        run: npm run build
        env:
          NODE_ENV: production

      - name: Create deployment package
        run: |
          # Create deployment directory
          mkdir deployment-package

          # Copy built application
          cp -r .next deployment-package/

          # Copy static assets
          cp -r public deployment-package/ || echo "No public directory found"

          # Copy essential files
          cp package.json deployment-package/
          cp package-lock.json deployment-package/
          cp server.js deployment-package/
          cp web.config deployment-package/

          # Copy source code (needed for custom server)
          cp -r app deployment-package/
          cp -r components deployment-package/

          # Copy config files
          cp next.config.js deployment-package/
          cp tailwind.config.js deployment-package/
          cp postcss.config.js deployment-package/
          cp tsconfig.json deployment-package/
          cp next-env.d.ts deployment-package/

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: deployment-package/ # Only upload what's needed

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_FBC8BD88FA5B4BBDAF275906EDB6017F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_ACF8CB99DDA146679E8338D66ECCD967 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_5C4654F5D61F4EA09FCE1751AAB65A9B }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: "Production"
          package: .
